# Generated by Django 5.2 on 2025-05-04 15:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название типа')),
                ('description', models.TextField(blank=True, verbose_name='Описание типа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тип батарейки',
                'verbose_name_plural': 'Типы батареек',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Название производителя батарейки', max_length=100, verbose_name='Бренд')),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Емкость должна быть больше 0'), django.core.validators.MaxValueValidator(100000, message='Емкость не может быть больше 100000 мАч')], verbose_name='Емкость (мАч)')),
                ('rechargeable', models.BooleanField(default=False, verbose_name='Перезаряжаемая')),
                ('voltage', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1, message='Напряжение должно быть больше 0.1В'), django.core.validators.MaxValueValidator(100, message='Напряжение не может быть больше 100В')], verbose_name='Напряжение (В)')),
                ('description', models.TextField(blank=True, help_text='Подробное описание батарейки', verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batteries', to='catalog.batterytype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Батарейка',
                'verbose_name_plural': 'Батарейки',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='capacity_positive'), models.CheckConstraint(condition=models.Q(('voltage__gt', 0), ('voltage__isnull', True), _connector='OR'), name='voltage_positive')],
            },
        ),
    ]
