# Generated by Django 5.2 on 2025-05-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_battery_large_wholesale_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='permissions',
            field=models.JSONField(default=dict),
        ),
    ]
