# Generated by Django 5.2 on 2025-05-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_userrole_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='permissions',
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_delete_batteries',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_delete_orders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_edit_batteries',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_edit_orders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_view_batteries',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_view_orders',
            field=models.BooleanField(default=False),
        ),
    ]
