# Generated by Django 5.2 on 2025-05-21 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_userrole_permissions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrole',
            old_name='can_delete_batteries',
            new_name='can_create_shipment',
        ),
        migrations.RenameField(
            model_name='userrole',
            old_name='can_delete_orders',
            new_name='can_do_everything',
        ),
        migrations.RenameField(
            model_name='userrole',
            old_name='can_edit_batteries',
            new_name='can_edit_battery_description',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='can_edit_orders',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='can_view_orders',
        ),
    ]
