version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - DATABASE_URL=mssql://sa:YourStrong@Passw0rd@db:1433/postgres
    depends_on:
      - db

  nginx:
    image: nginx:1.21
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - web

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    volumes:
      - sqlserver_data:/var/opt/mssql
    ports:
      - "1433:1433"

volumes:
  static_volume:
  media_volume:
  sqlserver_data: